import React from 'react';
import type { Metadata, Viewport } from 'next';
import './globals.css';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Tints the iOS status bar and the Android task switcher to match the
  // dark ground the app defaults to.
  themeColor: '#0C0C0C', // formatting-ok: browser chrome, read before CSS loads — can't be a var()
};

export const metadata: Metadata = {
  title: {
    default: 'theory.golf',
    template: '%s — theory.golf',
  },
  description: 'The intelligence layer for collegiate golf.',
  manifest: '/manifest.webmanifest',
  /* Generated by scripts/generate-icons.mjs — see that file to change the mark. */
  icons: {
    icon: [
      { url: '/icon.svg', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: '32x32' },
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
  },
  appleWebApp: {
    // Added to the iPhone home screen, the site launches without Safari's
    // chrome and shows the T mark instead of a screenshot thumbnail.
    capable: true,
    title: 'Theory Golf',
    statusBarStyle: 'black',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/*
          Next emits the standardised `mobile-web-app-capable` for
          appleWebApp.capable. Older iOS only recognises the prefixed name,
          so it's declared here too — without it the home-screen launch
          falls back to opening inside Safari's chrome.
        */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        {/*
          Flash-prevention: runs synchronously before first paint.
          If user has saved a light preference, applies it instantly
          so there's no dark→light flicker on page load.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('tg-theme');if(t==='light')document.documentElement.setAttribute('data-theme','light');}catch(e){}})();`,
          }}
        />
      </head>
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
