import type { MetadataRoute } from 'next';

/**
 * Served at /manifest.webmanifest. This is what turns the site into an
 * installable app: `standalone` drops the browser chrome when it's opened
 * from the home screen, and `short_name` is the label under the icon.
 *
 * Icons are generated by scripts/generate-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Theory Golf',
    short_name: 'Theory Golf',
    description: 'The intelligence layer for collegiate golf.',
    start_url: '/',
    display: 'standalone',
    // Matches --background in the dark theme, which is the default.
    background_color: '#0C0C0C', // formatting-ok: OS-level chrome, no CSS in scope
    theme_color: '#0C0C0C', // formatting-ok: OS-level chrome, no CSS in scope
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
      // `maskable` lets Android crop to its own shape without clipping the
      // mark — the ground is full-bleed, so the T survives any mask.
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
